language: go
go:
  - 1.13.x
os:
  - linux
  - windows
sudo: true
before_install:
  - go mod tidy
script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - i@sjis.me
    on_success: always
    on_failure: always